module.exports = {
  LOGIN_USER_FAILED: 'LOGIN_USER_FAILED',
  LOGIN_USER_PENDING: 'LOGIN_USER_PENDING',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  REFRESH_AUTH_STATE: 'REFRESH_AUTH_STATE',
  REGISTER_USER_FAILED: 'REGISTER_USER_FAILED',
  REGISTER_USER_PENDING: 'REGISTER_USER_PENDING',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
};
